### ISSUE TITLE
adding portableText in Page Sections returns an error

### ISSUE THREAD

**Issue by menkari** [OnecodexGitHubAdmin/sanity-template-angular-website#5]
I'm relatively new to Sanity Studio and I'm attempting to build out a site using this template, but I've run into a problem which I require some assistance with.

After creating a new site template from the following URL: `https://www.sanity.io/create` and following the setup procedures in the README.md file, starting the studio and making a basic edit an existing page returns an error:

Steps to reproduce:

1. Login
2. Scroll to 'Recently Edited', select `Template Blog`
3. Scroll to Page Sections, click `+ Add Item...`
4. Click `Portable Text` 

The following error message is displayed: `Error: Invalid item type: "[object Object]". Default array input can only contain objects (for now)`

**Comment by OnecodexGitHubAdmin** [comment]
Hi Matthew

Thanks a lot for creating this issue. First of all I'm happy that you use the angular starter template.
Actually this is an issue in the starter template which I provide.
You should remove portableText from the page sections array in apps/studio/schemas/documents/page.js
![image](https://user-images.githubusercontent.com/20403094/124547053-d7c67680-de2b-11eb-8604-83549af25c3b.png)

Then you won't be able to add portable text as page section anymore. If you want to add it again you should nest it into another object
The problem is that sanity studio doesn't accept nested arrays. Since page sections and portable text are both of type array the error occurs.

Let me know if this helps.
Also please let me know if you encounter any other issues or if you find some parts which could be improved.

**Comment by menkari** [comment]
Hi @OnecodexGitHubAdmin ,

Thanks for coming back to me so quickly!! I figured as much when I started looking at the schema definitions just now and seeing that only type: 'object' where compatible. So this means, I can only implement `portableText` as a field only within the schema at this point in time.
